---
- name: "Install Tmux"
  ansible.builtin.apt: 
    name: 
      - tmux
      - xclip
    state: present
  become: yes

- name: "Copying Tmux Config"
  copy:
    src: "{{ role_path }}/files/tmux.conf"
    dest: "{{ ansible_env.HOME}}/.config/tmux/"

- name: "Install TPM for tmux"
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: {{ ansible_env.HOME}}/.config/tmux//plugins/tpm
  become: no

- name: "Install Power Theme (git)"
  ansible.builtin.git:
    repo: https://github.com/wfxr/tmux-power.git
    dest: {{ ansible_env.HOME}}/.config/tmux/plugins/power/
  become: no

- name: "Install tmux plugins"
  ansible.builtin.shell: |
    export TMUX_PLUGIN_MANAGER_PATH="{{ ansible_env.HOME }}/.config/tmux/plugins"
    tmux start-server
    tmux new-session -d -s ansible_setup
    tmux source-file {{ ansible_env.HOME }}/.config/tmux/tmux.conf
    {{ ansible_env.HOME }}/.config/tmux/plugins/tpm/bin/install_plugins
    tmux kill-session -t ansible_setup
  become: no
  register: tpm_install
  changed_when: tpm_install.rc == 0


- name: "Verify tmux config loads"
  ansible.builtin.shell: |
    tmux start-server && tmux new-session -d -s ansible_setup || true
    tmux source-file {{ ansible_env.HOME }}/.config/tmux/tmux.conf
    tmux kill-session -t ansible_setup || true
  become: no
  register: tmux_source
  failed_when: tmux_source.rc != 0
