---
- name: Set global Git user name
  git_config:
    name: user.name
    scope: global
    value: "MrChristianL"

- name: Set global Git user email
  git_config:
    name: user.email
    scope: global
    value: "mrchristianleonard@gmail.com"

- name: "Ensure .ssh directory exists"
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: '0700'

- name: "Generating Ed25519 SSH key for GitHub"
  command: ssh-keygen -t ed25519 -f {{ ansible_env.HOME }}/.ssh/id_ed25519 -N ""
  args:
    creates: "{{ ansible_env.HOME }}/.ssh/id_ed25519"

- name: "-- SSH PUBLIC KEY --"
  command: cat "{{ ansible_env.HOME }}/.ssh/id_ed25519.pub"
  register: ssh_pubkey

- debug:
    msg: "Add this SSH key to GitHub: {{ ssh_pubkey.stdout }}"
