---

- name: Ensure fonts directory exists
  file:
    path: "/usr/local/share/fonts/JetBrainsMono"
    state: directory
    mode: '0755'
  become: yes

- name: Download JetBrainsMono Nerd Font
  get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.tar.xz"
    dest: "/tmp/JetBrainsMono.tar.xz"
    mode: '0644'
  become: yes

- name: Extract JetBrainsMono Nerd Font
  ansible.builtin.unarchive:
    src: "/tmp/JetBrainsMono.tar.xz"
    dest: "/usr/local/share/fonts/JetBrainsMono"
    remote_src: yes
  become: yes

- name: Refresh font cache
  command: fc-cache -fv

